#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo0425
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="master")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertt_cinema(t_cinema instance);
    partial void Updatet_cinema(t_cinema instance);
    partial void Deletet_cinema(t_cinema instance);
    partial void Insertt_film(t_film instance);
    partial void Updatet_film(t_film instance);
    partial void Deletet_film(t_film instance);
    partial void Insertt_room(t_room instance);
    partial void Updatet_room(t_room instance);
    partial void Deletet_room(t_room instance);
    partial void Insertt_seat(t_seat instance);
    partial void Updatet_seat(t_seat instance);
    partial void Deletet_seat(t_seat instance);
    partial void Insertt_plan(t_plan instance);
    partial void Updatet_plan(t_plan instance);
    partial void Deletet_plan(t_plan instance);
    partial void Insertt_reserve(t_reserve instance);
    partial void Updatet_reserve(t_reserve instance);
    partial void Deletet_reserve(t_reserve instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Demo0425.Properties.Settings.Default.masterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_dict> t_dict
		{
			get
			{
				return this.GetTable<t_dict>();
			}
		}
		
		public System.Data.Linq.Table<t_cinema> t_cinema
		{
			get
			{
				return this.GetTable<t_cinema>();
			}
		}
		
		public System.Data.Linq.Table<t_oper> t_oper
		{
			get
			{
				return this.GetTable<t_oper>();
			}
		}
		
		public System.Data.Linq.Table<t_film> t_film
		{
			get
			{
				return this.GetTable<t_film>();
			}
		}
		
		public System.Data.Linq.Table<t_room> t_room
		{
			get
			{
				return this.GetTable<t_room>();
			}
		}
		
		public System.Data.Linq.Table<t_seat> t_seat
		{
			get
			{
				return this.GetTable<t_seat>();
			}
		}
		
		public System.Data.Linq.Table<t_plan> t_plan
		{
			get
			{
				return this.GetTable<t_plan>();
			}
		}
		
		public System.Data.Linq.Table<t_reserve> t_reserve
		{
			get
			{
				return this.GetTable<t_reserve>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_dict")]
	public partial class t_dict
	{
		
		private int _enum_type;
		
		private int _enum_id;
		
		private string _enum_value;
		
		private string _enum_desc;
		
		private System.Nullable<System.DateTime> _create_time;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _create_oper;
		
		private string _update_oper;
		
		public t_dict()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enum_type", DbType="Int NOT NULL")]
		public int enum_type
		{
			get
			{
				return this._enum_type;
			}
			set
			{
				if ((this._enum_type != value))
				{
					this._enum_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enum_id", DbType="Int NOT NULL")]
		public int enum_id
		{
			get
			{
				return this._enum_id;
			}
			set
			{
				if ((this._enum_id != value))
				{
					this._enum_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enum_value", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string enum_value
		{
			get
			{
				return this._enum_value;
			}
			set
			{
				if ((this._enum_value != value))
				{
					this._enum_value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enum_desc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string enum_desc
		{
			get
			{
				return this._enum_desc;
			}
			set
			{
				if ((this._enum_desc != value))
				{
					this._enum_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this._create_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this._update_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_oper", DbType="VarChar(20)")]
		public string create_oper
		{
			get
			{
				return this._create_oper;
			}
			set
			{
				if ((this._create_oper != value))
				{
					this._create_oper = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_oper", DbType="VarChar(20)")]
		public string update_oper
		{
			get
			{
				return this._update_oper;
			}
			set
			{
				if ((this._update_oper != value))
				{
					this._update_oper = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_cinema")]
	public partial class t_cinema : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cinema_id;
		
		private string _cinema_name;
		
		private string _cinema_addr;
		
		private string _cinema_tel;
		
		private System.DateTime _create_time;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _create_oper;
		
		private string _update_oper;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncinema_idChanging(int value);
    partial void Oncinema_idChanged();
    partial void Oncinema_nameChanging(string value);
    partial void Oncinema_nameChanged();
    partial void Oncinema_addrChanging(string value);
    partial void Oncinema_addrChanged();
    partial void Oncinema_telChanging(string value);
    partial void Oncinema_telChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Oncreate_operChanging(string value);
    partial void Oncreate_operChanged();
    partial void Onupdate_operChanging(string value);
    partial void Onupdate_operChanged();
    #endregion
		
		public t_cinema()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinema_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cinema_id
		{
			get
			{
				return this._cinema_id;
			}
			set
			{
				if ((this._cinema_id != value))
				{
					this.Oncinema_idChanging(value);
					this.SendPropertyChanging();
					this._cinema_id = value;
					this.SendPropertyChanged("cinema_id");
					this.Oncinema_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinema_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cinema_name
		{
			get
			{
				return this._cinema_name;
			}
			set
			{
				if ((this._cinema_name != value))
				{
					this.Oncinema_nameChanging(value);
					this.SendPropertyChanging();
					this._cinema_name = value;
					this.SendPropertyChanged("cinema_name");
					this.Oncinema_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinema_addr", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string cinema_addr
		{
			get
			{
				return this._cinema_addr;
			}
			set
			{
				if ((this._cinema_addr != value))
				{
					this.Oncinema_addrChanging(value);
					this.SendPropertyChanging();
					this._cinema_addr = value;
					this.SendPropertyChanged("cinema_addr");
					this.Oncinema_addrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinema_tel", DbType="VarChar(30)")]
		public string cinema_tel
		{
			get
			{
				return this._cinema_tel;
			}
			set
			{
				if ((this._cinema_tel != value))
				{
					this.Oncinema_telChanging(value);
					this.SendPropertyChanging();
					this._cinema_tel = value;
					this.SendPropertyChanged("cinema_tel");
					this.Oncinema_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_oper", DbType="VarChar(20)")]
		public string create_oper
		{
			get
			{
				return this._create_oper;
			}
			set
			{
				if ((this._create_oper != value))
				{
					this.Oncreate_operChanging(value);
					this.SendPropertyChanging();
					this._create_oper = value;
					this.SendPropertyChanged("create_oper");
					this.Oncreate_operChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_oper", DbType="VarChar(20)")]
		public string update_oper
		{
			get
			{
				return this._update_oper;
			}
			set
			{
				if ((this._update_oper != value))
				{
					this.Onupdate_operChanging(value);
					this.SendPropertyChanging();
					this._update_oper = value;
					this.SendPropertyChanged("update_oper");
					this.Onupdate_operChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_oper")]
	public partial class t_oper
	{
		
		private string _oper_no;
		
		private string _oper_name;
		
		private string _password;
		
		private System.DateTime _create_time;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _create_oper;
		
		private string _update_oper;
		
		public t_oper()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oper_no", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string oper_no
		{
			get
			{
				return this._oper_no;
			}
			set
			{
				if ((this._oper_no != value))
				{
					this._oper_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oper_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string oper_name
		{
			get
			{
				return this._oper_name;
			}
			set
			{
				if ((this._oper_name != value))
				{
					this._oper_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this._create_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this._update_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_oper", DbType="VarChar(20)")]
		public string create_oper
		{
			get
			{
				return this._create_oper;
			}
			set
			{
				if ((this._create_oper != value))
				{
					this._create_oper = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_oper", DbType="VarChar(20)")]
		public string update_oper
		{
			get
			{
				return this._update_oper;
			}
			set
			{
				if ((this._update_oper != value))
				{
					this._update_oper = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_film")]
	public partial class t_film : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _film_id;
		
		private string _film_name;
		
		private int _film_type_id;
		
		private string _film_desc;
		
		private string _film_pic_url;
		
		private string _film_video_url;
		
		private int _film_status;
		
		private System.Nullable<System.DateTime> _film_up_time;
		
		private System.Nullable<System.DateTime> _film_down_time;
		
		private System.DateTime _create_time;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _create_oper;
		
		private string _update_oper;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfilm_idChanging(int value);
    partial void Onfilm_idChanged();
    partial void Onfilm_nameChanging(string value);
    partial void Onfilm_nameChanged();
    partial void Onfilm_type_idChanging(int value);
    partial void Onfilm_type_idChanged();
    partial void Onfilm_descChanging(string value);
    partial void Onfilm_descChanged();
    partial void Onfilm_pic_urlChanging(string value);
    partial void Onfilm_pic_urlChanged();
    partial void Onfilm_video_urlChanging(string value);
    partial void Onfilm_video_urlChanged();
    partial void Onfilm_statusChanging(int value);
    partial void Onfilm_statusChanged();
    partial void Onfilm_up_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onfilm_up_timeChanged();
    partial void Onfilm_down_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onfilm_down_timeChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Oncreate_operChanging(string value);
    partial void Oncreate_operChanged();
    partial void Onupdate_operChanging(string value);
    partial void Onupdate_operChanged();
    #endregion
		
		public t_film()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int film_id
		{
			get
			{
				return this._film_id;
			}
			set
			{
				if ((this._film_id != value))
				{
					this.Onfilm_idChanging(value);
					this.SendPropertyChanging();
					this._film_id = value;
					this.SendPropertyChanged("film_id");
					this.Onfilm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string film_name
		{
			get
			{
				return this._film_name;
			}
			set
			{
				if ((this._film_name != value))
				{
					this.Onfilm_nameChanging(value);
					this.SendPropertyChanging();
					this._film_name = value;
					this.SendPropertyChanged("film_name");
					this.Onfilm_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_type_id", DbType="Int NOT NULL")]
		public int film_type_id
		{
			get
			{
				return this._film_type_id;
			}
			set
			{
				if ((this._film_type_id != value))
				{
					this.Onfilm_type_idChanging(value);
					this.SendPropertyChanging();
					this._film_type_id = value;
					this.SendPropertyChanged("film_type_id");
					this.Onfilm_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_desc", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string film_desc
		{
			get
			{
				return this._film_desc;
			}
			set
			{
				if ((this._film_desc != value))
				{
					this.Onfilm_descChanging(value);
					this.SendPropertyChanging();
					this._film_desc = value;
					this.SendPropertyChanged("film_desc");
					this.Onfilm_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_pic_url", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string film_pic_url
		{
			get
			{
				return this._film_pic_url;
			}
			set
			{
				if ((this._film_pic_url != value))
				{
					this.Onfilm_pic_urlChanging(value);
					this.SendPropertyChanging();
					this._film_pic_url = value;
					this.SendPropertyChanged("film_pic_url");
					this.Onfilm_pic_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_video_url", DbType="VarChar(255)")]
		public string film_video_url
		{
			get
			{
				return this._film_video_url;
			}
			set
			{
				if ((this._film_video_url != value))
				{
					this.Onfilm_video_urlChanging(value);
					this.SendPropertyChanging();
					this._film_video_url = value;
					this.SendPropertyChanged("film_video_url");
					this.Onfilm_video_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_status", DbType="Int NOT NULL")]
		public int film_status
		{
			get
			{
				return this._film_status;
			}
			set
			{
				if ((this._film_status != value))
				{
					this.Onfilm_statusChanging(value);
					this.SendPropertyChanging();
					this._film_status = value;
					this.SendPropertyChanged("film_status");
					this.Onfilm_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_up_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> film_up_time
		{
			get
			{
				return this._film_up_time;
			}
			set
			{
				if ((this._film_up_time != value))
				{
					this.Onfilm_up_timeChanging(value);
					this.SendPropertyChanging();
					this._film_up_time = value;
					this.SendPropertyChanged("film_up_time");
					this.Onfilm_up_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_down_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> film_down_time
		{
			get
			{
				return this._film_down_time;
			}
			set
			{
				if ((this._film_down_time != value))
				{
					this.Onfilm_down_timeChanging(value);
					this.SendPropertyChanging();
					this._film_down_time = value;
					this.SendPropertyChanged("film_down_time");
					this.Onfilm_down_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_oper", DbType="VarChar(20)")]
		public string create_oper
		{
			get
			{
				return this._create_oper;
			}
			set
			{
				if ((this._create_oper != value))
				{
					this.Oncreate_operChanging(value);
					this.SendPropertyChanging();
					this._create_oper = value;
					this.SendPropertyChanged("create_oper");
					this.Oncreate_operChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_oper", DbType="VarChar(20)")]
		public string update_oper
		{
			get
			{
				return this._update_oper;
			}
			set
			{
				if ((this._update_oper != value))
				{
					this.Onupdate_operChanging(value);
					this.SendPropertyChanging();
					this._update_oper = value;
					this.SendPropertyChanged("update_oper");
					this.Onupdate_operChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_room")]
	public partial class t_room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _room_id;
		
		private decimal _cinema_id;
		
		private string _room_name;
		
		private System.DateTime _create_time;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _create_oper;
		
		private string _update_oper;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onroom_idChanging(int value);
    partial void Onroom_idChanged();
    partial void Oncinema_idChanging(decimal value);
    partial void Oncinema_idChanged();
    partial void Onroom_nameChanging(string value);
    partial void Onroom_nameChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Oncreate_operChanging(string value);
    partial void Oncreate_operChanged();
    partial void Onupdate_operChanging(string value);
    partial void Onupdate_operChanged();
    #endregion
		
		public t_room()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int room_id
		{
			get
			{
				return this._room_id;
			}
			set
			{
				if ((this._room_id != value))
				{
					this.Onroom_idChanging(value);
					this.SendPropertyChanging();
					this._room_id = value;
					this.SendPropertyChanged("room_id");
					this.Onroom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinema_id", DbType="Decimal(8,0) NOT NULL")]
		public decimal cinema_id
		{
			get
			{
				return this._cinema_id;
			}
			set
			{
				if ((this._cinema_id != value))
				{
					this.Oncinema_idChanging(value);
					this.SendPropertyChanging();
					this._cinema_id = value;
					this.SendPropertyChanged("cinema_id");
					this.Oncinema_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string room_name
		{
			get
			{
				return this._room_name;
			}
			set
			{
				if ((this._room_name != value))
				{
					this.Onroom_nameChanging(value);
					this.SendPropertyChanging();
					this._room_name = value;
					this.SendPropertyChanged("room_name");
					this.Onroom_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_oper", DbType="VarChar(20)")]
		public string create_oper
		{
			get
			{
				return this._create_oper;
			}
			set
			{
				if ((this._create_oper != value))
				{
					this.Oncreate_operChanging(value);
					this.SendPropertyChanging();
					this._create_oper = value;
					this.SendPropertyChanged("create_oper");
					this.Oncreate_operChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_oper", DbType="VarChar(20)")]
		public string update_oper
		{
			get
			{
				return this._update_oper;
			}
			set
			{
				if ((this._update_oper != value))
				{
					this.Onupdate_operChanging(value);
					this.SendPropertyChanging();
					this._update_oper = value;
					this.SendPropertyChanged("update_oper");
					this.Onupdate_operChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_seat")]
	public partial class t_seat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _seat_id;
		
		private decimal _room_id;
		
		private int _row_num;
		
		private int _col_num;
		
		private int _seat_flag;
		
		private System.DateTime _create_time;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _create_oper;
		
		private string _update_oper;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onseat_idChanging(int value);
    partial void Onseat_idChanged();
    partial void Onroom_idChanging(decimal value);
    partial void Onroom_idChanged();
    partial void Onrow_numChanging(int value);
    partial void Onrow_numChanged();
    partial void Oncol_numChanging(int value);
    partial void Oncol_numChanged();
    partial void Onseat_flagChanging(int value);
    partial void Onseat_flagChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Oncreate_operChanging(string value);
    partial void Oncreate_operChanged();
    partial void Onupdate_operChanging(string value);
    partial void Onupdate_operChanged();
    #endregion
		
		public t_seat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seat_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int seat_id
		{
			get
			{
				return this._seat_id;
			}
			set
			{
				if ((this._seat_id != value))
				{
					this.Onseat_idChanging(value);
					this.SendPropertyChanging();
					this._seat_id = value;
					this.SendPropertyChanged("seat_id");
					this.Onseat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_id", DbType="Decimal(8,0) NOT NULL")]
		public decimal room_id
		{
			get
			{
				return this._room_id;
			}
			set
			{
				if ((this._room_id != value))
				{
					this.Onroom_idChanging(value);
					this.SendPropertyChanging();
					this._room_id = value;
					this.SendPropertyChanged("room_id");
					this.Onroom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_row_num", DbType="Int NOT NULL")]
		public int row_num
		{
			get
			{
				return this._row_num;
			}
			set
			{
				if ((this._row_num != value))
				{
					this.Onrow_numChanging(value);
					this.SendPropertyChanging();
					this._row_num = value;
					this.SendPropertyChanged("row_num");
					this.Onrow_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_col_num", DbType="Int NOT NULL")]
		public int col_num
		{
			get
			{
				return this._col_num;
			}
			set
			{
				if ((this._col_num != value))
				{
					this.Oncol_numChanging(value);
					this.SendPropertyChanging();
					this._col_num = value;
					this.SendPropertyChanged("col_num");
					this.Oncol_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seat_flag", DbType="Int NOT NULL")]
		public int seat_flag
		{
			get
			{
				return this._seat_flag;
			}
			set
			{
				if ((this._seat_flag != value))
				{
					this.Onseat_flagChanging(value);
					this.SendPropertyChanging();
					this._seat_flag = value;
					this.SendPropertyChanged("seat_flag");
					this.Onseat_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_oper", DbType="VarChar(20)")]
		public string create_oper
		{
			get
			{
				return this._create_oper;
			}
			set
			{
				if ((this._create_oper != value))
				{
					this.Oncreate_operChanging(value);
					this.SendPropertyChanging();
					this._create_oper = value;
					this.SendPropertyChanged("create_oper");
					this.Oncreate_operChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_oper", DbType="VarChar(20)")]
		public string update_oper
		{
			get
			{
				return this._update_oper;
			}
			set
			{
				if ((this._update_oper != value))
				{
					this.Onupdate_operChanging(value);
					this.SendPropertyChanging();
					this._update_oper = value;
					this.SendPropertyChanged("update_oper");
					this.Onupdate_operChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_plan")]
	public partial class t_plan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _plan_id;
		
		private decimal _film_id;
		
		private decimal _room_id;
		
		private decimal _ticket_price;
		
		private System.DateTime _begin_time;
		
		private System.DateTime _end_time;
		
		private int _plan_status;
		
		private System.Nullable<System.DateTime> _create_time;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _create_oper;
		
		private string _update_oper;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onplan_idChanging(int value);
    partial void Onplan_idChanged();
    partial void Onfilm_idChanging(decimal value);
    partial void Onfilm_idChanged();
    partial void Onroom_idChanging(decimal value);
    partial void Onroom_idChanged();
    partial void Onticket_priceChanging(decimal value);
    partial void Onticket_priceChanged();
    partial void Onbegin_timeChanging(System.DateTime value);
    partial void Onbegin_timeChanged();
    partial void Onend_timeChanging(System.DateTime value);
    partial void Onend_timeChanged();
    partial void Onplan_statusChanging(int value);
    partial void Onplan_statusChanged();
    partial void Oncreate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_timeChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Oncreate_operChanging(string value);
    partial void Oncreate_operChanged();
    partial void Onupdate_operChanging(string value);
    partial void Onupdate_operChanged();
    #endregion
		
		public t_plan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int plan_id
		{
			get
			{
				return this._plan_id;
			}
			set
			{
				if ((this._plan_id != value))
				{
					this.Onplan_idChanging(value);
					this.SendPropertyChanging();
					this._plan_id = value;
					this.SendPropertyChanged("plan_id");
					this.Onplan_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_film_id", DbType="Decimal(8,0) NOT NULL")]
		public decimal film_id
		{
			get
			{
				return this._film_id;
			}
			set
			{
				if ((this._film_id != value))
				{
					this.Onfilm_idChanging(value);
					this.SendPropertyChanging();
					this._film_id = value;
					this.SendPropertyChanged("film_id");
					this.Onfilm_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_id", DbType="Decimal(8,0) NOT NULL")]
		public decimal room_id
		{
			get
			{
				return this._room_id;
			}
			set
			{
				if ((this._room_id != value))
				{
					this.Onroom_idChanging(value);
					this.SendPropertyChanging();
					this._room_id = value;
					this.SendPropertyChanged("room_id");
					this.Onroom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ticket_price", DbType="Decimal(16,2) NOT NULL")]
		public decimal ticket_price
		{
			get
			{
				return this._ticket_price;
			}
			set
			{
				if ((this._ticket_price != value))
				{
					this.Onticket_priceChanging(value);
					this.SendPropertyChanging();
					this._ticket_price = value;
					this.SendPropertyChanged("ticket_price");
					this.Onticket_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_begin_time", DbType="DateTime NOT NULL")]
		public System.DateTime begin_time
		{
			get
			{
				return this._begin_time;
			}
			set
			{
				if ((this._begin_time != value))
				{
					this.Onbegin_timeChanging(value);
					this.SendPropertyChanging();
					this._begin_time = value;
					this.SendPropertyChanged("begin_time");
					this.Onbegin_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="DateTime NOT NULL")]
		public System.DateTime end_time
		{
			get
			{
				return this._end_time;
			}
			set
			{
				if ((this._end_time != value))
				{
					this.Onend_timeChanging(value);
					this.SendPropertyChanging();
					this._end_time = value;
					this.SendPropertyChanged("end_time");
					this.Onend_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_status", DbType="Int NOT NULL")]
		public int plan_status
		{
			get
			{
				return this._plan_status;
			}
			set
			{
				if ((this._plan_status != value))
				{
					this.Onplan_statusChanging(value);
					this.SendPropertyChanging();
					this._plan_status = value;
					this.SendPropertyChanged("plan_status");
					this.Onplan_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_oper", DbType="VarChar(20)")]
		public string create_oper
		{
			get
			{
				return this._create_oper;
			}
			set
			{
				if ((this._create_oper != value))
				{
					this.Oncreate_operChanging(value);
					this.SendPropertyChanging();
					this._create_oper = value;
					this.SendPropertyChanged("create_oper");
					this.Oncreate_operChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_oper", DbType="VarChar(20)")]
		public string update_oper
		{
			get
			{
				return this._update_oper;
			}
			set
			{
				if ((this._update_oper != value))
				{
					this.Onupdate_operChanging(value);
					this.SendPropertyChanging();
					this._update_oper = value;
					this.SendPropertyChanged("update_oper");
					this.Onupdate_operChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_reserve")]
	public partial class t_reserve : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _reserve_id;
		
		private decimal _plan_id;
		
		private decimal _seat_id;
		
		private int _reserve_status;
		
		private System.DateTime _create_time;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _create_oper;
		
		private string _update_oper;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onreserve_idChanging(int value);
    partial void Onreserve_idChanged();
    partial void Onplan_idChanging(decimal value);
    partial void Onplan_idChanged();
    partial void Onseat_idChanging(decimal value);
    partial void Onseat_idChanged();
    partial void Onreserve_statusChanging(int value);
    partial void Onreserve_statusChanged();
    partial void Oncreate_timeChanging(System.DateTime value);
    partial void Oncreate_timeChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Oncreate_operChanging(string value);
    partial void Oncreate_operChanged();
    partial void Onupdate_operChanging(string value);
    partial void Onupdate_operChanged();
    #endregion
		
		public t_reserve()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reserve_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int reserve_id
		{
			get
			{
				return this._reserve_id;
			}
			set
			{
				if ((this._reserve_id != value))
				{
					this.Onreserve_idChanging(value);
					this.SendPropertyChanging();
					this._reserve_id = value;
					this.SendPropertyChanged("reserve_id");
					this.Onreserve_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_id", DbType="Decimal(8,0) NOT NULL")]
		public decimal plan_id
		{
			get
			{
				return this._plan_id;
			}
			set
			{
				if ((this._plan_id != value))
				{
					this.Onplan_idChanging(value);
					this.SendPropertyChanging();
					this._plan_id = value;
					this.SendPropertyChanged("plan_id");
					this.Onplan_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seat_id", DbType="Decimal(8,0) NOT NULL")]
		public decimal seat_id
		{
			get
			{
				return this._seat_id;
			}
			set
			{
				if ((this._seat_id != value))
				{
					this.Onseat_idChanging(value);
					this.SendPropertyChanging();
					this._seat_id = value;
					this.SendPropertyChanged("seat_id");
					this.Onseat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reserve_status", DbType="Int NOT NULL")]
		public int reserve_status
		{
			get
			{
				return this._reserve_status;
			}
			set
			{
				if ((this._reserve_status != value))
				{
					this.Onreserve_statusChanging(value);
					this.SendPropertyChanging();
					this._reserve_status = value;
					this.SendPropertyChanged("reserve_status");
					this.Onreserve_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_time", DbType="DateTime NOT NULL")]
		public System.DateTime create_time
		{
			get
			{
				return this._create_time;
			}
			set
			{
				if ((this._create_time != value))
				{
					this.Oncreate_timeChanging(value);
					this.SendPropertyChanging();
					this._create_time = value;
					this.SendPropertyChanged("create_time");
					this.Oncreate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_oper", DbType="VarChar(20)")]
		public string create_oper
		{
			get
			{
				return this._create_oper;
			}
			set
			{
				if ((this._create_oper != value))
				{
					this.Oncreate_operChanging(value);
					this.SendPropertyChanging();
					this._create_oper = value;
					this.SendPropertyChanged("create_oper");
					this.Oncreate_operChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_oper", DbType="VarChar(20)")]
		public string update_oper
		{
			get
			{
				return this._update_oper;
			}
			set
			{
				if ((this._update_oper != value))
				{
					this.Onupdate_operChanging(value);
					this.SendPropertyChanging();
					this._update_oper = value;
					this.SendPropertyChanged("update_oper");
					this.Onupdate_operChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
